group: edge
language: node_js

services: 
  - docker

before_install:
  - docker pull rethinkdb
  - docker run -d -p 8080:8080 -p 28015:28015 -p 29015:29015 rethinkdb

before_script:
 - npm install -g coffee-script

script: npm test
