// Generated by CoffeeScript 1.9.0
module.exports = function(code, data, err) {
  return this.socket.emit("http_error", {
    code: code,
    message: err.message,
    raw: err,
    data: data,
    table: this.model._name,
    action: this.action
  });
};
