// Generated by CoffeeScript 1.9.0
var Bus, Mithink, t,
  __slice = [].slice;

t = require("thinky");

Bus = require('./bus');

Mithink = function() {
  var args;
  args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
  Mithink.$ = t.apply(t, args);
  Mithink.r = Mithink.$.r;
  Mithink.type = Mithink.$.type;
  Mithink.Query = Mithink.$.Query;
  Mithink.Errors = Mithink.$.Errors;
  return Mithink;
};

Mithink.bus = function(io) {
  Bus(io);
  return Mithink;
};

Mithink.proxy = function(method, args) {
  if (!Mithink.$) {
    throw new Error("thinky has not been initialized, please see http://thinky.io/documentation");
  }
  return Mithink.$[method].apply(Mithink.$, args);
};

Mithink.createModel = function() {
  var args, model;
  args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
  model = Mithink.proxy('createModel', args);
  Bus.extend(model).wireUp(model);
  return model;
};

module.exports = Mithink;
