// Generated by CoffeeScript 1.9.0
var Bus, Thinky, t,
  __slice = [].slice;

t = require("thinky");

Bus = require('./bus');

Thinky = function() {
  var args;
  args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
  Thinky.$ = t.apply(t, args);
  Thinky.r = Thinky.$.r;
  Thinky.type = Thinky.$.type;
  Thinky.Query = Thinky.$.Query;
  Thinky.Errors = Thinky.$.Errors;
  return Thinky;
};

Thinky.Bus = Bus;

Thinky.bus = function(io) {
  Thinky.Bus(io);
  return Thinky;
};

Thinky.proxy = function(method, args) {
  if (!Thinky.$) {
    throw new Error("thinky has not been initialized, please see http://thinky.io/documentation");
  }
  return Thinky.$[method].apply(Thinky.$, args);
};

Thinky.createModel = function() {
  var args, model;
  args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
  model = Thinky.proxy('createModel', args);
  Bus.extend(model).wireUp(model);
  return model;
};

module.exports = Thinky;
