// Generated by CoffeeScript 1.9.0
var m, pubs, subs;

m = require('mithril');

subs = "load upsert remove".split(' ');

pubs = "update destroy create".split(' ');

exports.wrap = function(Mithink) {
  Mithink.__tables__ = {};
  Mithink._table = function(name) {
    return Mithink.__tables__[name];
  };
  return Mithink.table = function(name) {
    var action, table, _fn, _fn1, _i, _j, _len, _len1;
    if (Mithink._table(name)) {
      return Mithink._table(name);
    }
    table = Mithink.__tables__[name] = new Mithink.adapter.Table;
    table.channel = Mithink.createConnection(name);
    _fn = function(action) {
      return table.channel.on(action, function(data) {
        table.handlers[action].call(table, data);
        if (Mithink.redraw) {
          return Mithink.redraw();
        }
      });
    };
    for (_i = 0, _len = subs.length; _i < _len; _i++) {
      action = subs[_i];
      _fn(action);
    }
    _fn1 = function(action) {
      return table[action] = function(data) {
        return table.channel.emit(action, data);
      };
    };
    for (_j = 0, _len1 = pubs.length; _j < _len1; _j++) {
      action = pubs[_j];
      _fn1(action);
    }
    return table;
  };
};
