// Generated by CoffeeScript 1.9.0
var Mithink, Mithril, extensions;

Mithril = require('./adapters/mithril');

extensions = require('./extensions');

Mithink = function(host, adapter) {
  if (Mithink.socket) {
    return Mithink;
  }
  Mithink.adapter = adapter || Mithril.init();
  Mithink.host = host || window.location.origin;
  Mithink.socket = Mithink.createConnection();
  return Mithink;
};

extensions.wrap(Mithink);

Mithink.createConnection = function(channel) {
  var location;
  location = [Mithink.host];
  if (channel) {
    location.push(channel);
  }
  return io(location.join('/'));
};

module.exports = Mithink;
