// Generated by CoffeeScript 1.9.0

/**
 * @title Universal detection
 * @text here we detect if we are on the server or the client
 */
module.exports = typeof window !== 'undefined' ? require('./client') : require('./server');
