// Generated by CoffeeScript 1.9.0
var Access_Control, utils,
  __slice = [].slice;

utils = require('../utils');

Access_Control = function(Bus) {
  Bus.__access_control__ = {};
  Bus.guard = function(opts) {
    var action, check, _i, _len, _ref, _results;
    _ref = Object.keys(opts);
    _results = [];
    for (check = _i = 0, _len = _ref.length; _i < _len; check = ++_i) {
      action = _ref[check];
      _results.push(Bus.__access_control__[utils.namespace(this.model._name, action)] = check);
    }
    return _results;
  };
  Bus.checkpoint = function(action) {
    return Bus.__access_control__[utils.namespace(this.model._name, this.action)];
  };
  return Bus.__protect__ = function(action) {
    var ctx;
    ctx = this;
    return function() {
      var args, checkpoint;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      if (checkpoint = Bus.checkpoint.call(ctx) && !checkpoint(this.socket)) {
        debug("unauthorized attempt to perform " + ctx.action + " on the " + ctx.model._name + " table");
        return ctx.socket.emit("http_error", {
          code: 403,
          message: "unauthorized attempt to perform " + ctx.action + " on the " + ctx.model._name + " table",
          table: ctx.model._name,
          action: ctx.action
        });
      }
      return action.apply(ctx, args);
    };
  };
};

module.exports = Access_Control;
