// Generated by CoffeeScript 1.9.0
var debug;

debug = require('debug')('mithink:actions');

exports.load = function() {
  debug("loading " + this.model._name + " table");
  return this.model.run().then((function(_this) {
    return function(data) {
      return _this.socket.emit("load", data);
    };
  })(this));
};

exports.update = function(data) {
  debug("updating " + data.id);
  debug(data);
  return this.model.save(data, {
    conflict: "update"
  })["catch"]((function(_this) {
    return function(err) {
      return _this.socket.emit("http_error", {
        code: 404,
        message: err.message,
        table: _this.table,
        action: _this.action
      });
    };
  })(this));
};

exports.destroy = function(data) {};

exports.create = function(data) {};
