// Generated by CoffeeScript 1.9.0
var __slice = [].slice;

exports.channelName = function(str) {
  return "/" + str;
};

exports.namespace = function() {
  var args;
  args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
  return args.join(':');
};

exports.isPlainObject = function(obj) {
  return Object.prototype.toString.call(obj) === '[object Object]';
};
