// Generated by CoffeeScript 1.9.0
var __slice = [].slice;

exports.channelName = function(str) {
  return "/" + str;
};

exports.namespace = function() {
  var args;
  args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
  return args.join(':');
};

exports.isPlainObject = function(obj) {
  return Object.prototype.toString.call(obj) === '[object Object]';
};

exports.shallowCopy = function(obj) {
  var key, n, val;
  n = {};
  for (key in obj) {
    val = obj[key];
    n[key] = val;
  }
  return n;
};

exports.keys = function(obj) {
  var key, keys, val;
  keys = [];
  for (key in obj) {
    val = obj[key];
    keys.push(key);
  }
  return keys;
};
