// Generated by CoffeeScript 1.9.0
var utils;

utils = {};

utils.LENGTH_MSG = "{{ REDACTED [length] }}";

utils.SENSITIVE_MSG = "{{ REDACTED [sensitive] }}";

utils.MAX_LENGTH = 150;

utils.redact = function(args) {
  if (args.length === 0) {
    return args;
  }
  return args.map(function(arg) {
    if (!arg) {
      return arg;
    }
    if (typeof arg.length && arg.length > utils.MAX_LENGTH) {
      return utils.LENGTH_MSG;
    }
    if (typeof arg === 'object') {
      return utils.redactObject(arg);
    }
    return arg;
  });
};

utils.redactObject = function(obj) {
  var k, n, v;
  n = {};
  for (k in obj) {
    v = obj[k];
    if (k === 'password') {
      n[k] = utils.SENSITIVE_MSG;
    } else if (v.length && v.length > utils.MAX_LENGTH) {
      n[k] = utils.LENGTH_MSG;
    } else if (typeof v === 'object') {
      n[k] = utils.redactObject(v);
    } else {
      n[k] = v;
    }
  }
  return n;
};

module.exports = utils.redact;
