// Generated by CoffeeScript 1.9.0
var Row, m;

m = require('mithril');

module.exports = Row = (function() {
  Row.create = function(attrs, table) {
    return new this(attrs, table);
  };

  function Row(attrs, table) {
    throw new Error("your adapter should overwrite the Row.constructor instance method");
  }

  Row.prototype.toJSON = function() {
    throw new Error("your adapter should overwrite the Row.toJSON instance method");
  };

  return Row;

})();
